menu:
  首页: /
  归档: /archives

widgets:
- search
- category
- tagcloud

excerpt_link: "Read More"

twitter:
  username:
  show_replies: false
  tweet_count: 5

jiathis:
  enable: true

fancybox: true

baidu_analytics:
rss:

